# This file defines the desired state of our IRIS configuration.
# As per the assignment requirement (Section 5.1), we parameterize the setup
# so it can be reused for different environments (DEV/SIT/UAT) without changing code.

namespace: TRAINING
globals_db: TRAININGDATA
routines_db: TRAININGCODE

web_apps:
  - /csp/training

production:
  class: TRAINING.Production
  auto_start: true

# Note: In a real environment, sensitive variables (like API passwords or credentials)
# should be stored in a separate `vault.yml` file encrypted with ansible-vault.