# CSP config file

LoadModule csp_module_sa /opt/webgateway/bin/CSPa24.so
CSPModulePath /opt/webgateway/bin/
CSPConfigPath /opt/webgateway/bin/

<Location />
    CSP On
</Location>

<Directory />
    Options MultiViews FollowSymLinks
    AllowOverride None
    Require all granted
    <FilesMatch "\.(log|ini|pid|exe|so)$">
        Require all denied
    </FilesMatch>
</Directory>

Redirect /csp/docbook/ http://docs.intersystems.com/irislatest/csp/docbook/
