all:
  children:
    iris_nodes:
      hosts:
        iris-uat-a:
          ansible_host: 10.0.30.11
          ansible_user: iris_automation
          iris_container: iris
          mirror_role: primary
        iris-uat-b:
          ansible_host: 10.0.30.12
          ansible_user: iris_automation
          iris_container: iris
          mirror_role: backup
    iris_primary:
      hosts:
        iris-uat-a: {}
    iris_backup:
      hosts:
        iris-uat-b: {}
