all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    shard_nodes:
      hosts:
        shard_data1:
          ansible_connection: local
          iris_container: shard_data1
          shard_role: node1
          shard_node_id: 1
          shard_host_ip: 172.29.0.10
          iris_superserver_port: 41773
        shard_data2:
          ansible_connection: local
          iris_container: shard_data2
          shard_role: data
          shard_node_id: 2
          shard_host_ip: 172.29.0.11
          iris_superserver_port: 43773
        shard_data3:
          ansible_connection: local
          iris_container: shard_data3
          shard_role: data
          shard_node_id: 3
          shard_host_ip: 172.29.0.12
          iris_superserver_port: 45773
    shard_node1:
      hosts:
        shard_data1: {}
    shard_data_nodes:
      hosts:
        shard_data2: {}
        shard_data3: {}
