---
- name: Configure mirror primary
  hosts: iris_primary
  become: false
  gather_facts: false

  roles:
    - iris_mirror_primary

- name: Configure mirror backup
  hosts: iris_backup
  become: false
  gather_facts: false

  roles:
    - iris_mirror_backup
